# Generated by Django 5.2.3 on 2025-06-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.FloatField(),
        ),
    ]
